mode: 'train'  # 'eval'

wav:
  sr: 32000 
  window_length: 1024
  hop_length: 640 
  n_mels: 64

encoder:
  model: 'audioset'  # 'deit'
  freeze: No
  pretrained: Yes

decoder:
  nhead: 8
  nhid: 512
  nlayers: 4
  dropout: 0.2
  dim_feedforward: 2048
  activation: 'gelu'

word_embedding:
  pretrained: Yes 
  freeze: No 

data:
  batch_size: 32
  num_workers: 8

training:
  label_smoothing: Yes
  epochs: 30
  lr: !!float 1e-4
  clip_grad: 2
  seed: 20

path:
  vocabulary: 'data/pickles/words_list.p'
  encoder: 'pretrained_models/audioset_deit.pth'  # 'pretrained_models/deit.pth'
  word2vec: 'pretrained_models/word2vec/w2v_512.model'
  eval_model: 'pretrained_models/ACTm.pth'
